import AuthSession from '@/components/provider/SessionProvider';
import '@/styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body>
        {' '}
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
